# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: build_and_deploy_web_to_110.99

on: 
  push:
    branches:
      - master
  workflow_dispatch

env:
  DOCKER_ACCESS_NAME: ${{ secrets.DOCKER_ACCESS_NAME }}
  DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
  PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
  HOST_IP_99: ${{ secrets.HOST_IP_99 }}
  HOST_ADMIN_99: ${{ secrets.HOST_ADMIN_99 }}

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: restore yarn
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: build
        run: ./sh/build_web_to_110.99.sh
      - name: deploy
        run: ./sh/deploy_web_to_110.99.sh
